# Generated by Django 2.2.4 on 2019-11-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Rather Not Say')], max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('city', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('interests', models.TextField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('status', models.IntegerField(default=0)),
                ('breakups', models.IntegerField(blank=True, default=0)),
                ('conquests', models.ManyToManyField(blank=True, related_name='conquests', to=settings.AUTH_USER_MODEL)),
                ('proposals', models.ManyToManyField(blank=True, related_name='proposals', to='matching.Proposal')),
                ('relationships', models.ManyToManyField(blank=True, related_name='relationships', to='matching.Relationship')),
                ('user', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
